/**
 * Cryptographic Utility for Kaivincia CRM
 * Uses Web Crypto API (AES-GCM 256-bit with PBKDF2 Key Derivation)
 * Native, cross-platform (Web browser + Node.js 18+ server environments)
 */

// Master project salt/passphrase derived for Kaivincia Firestore credentials
const DEFAULT_SALT_SEED = 'kaivincia-crm-telnyx-vault-2026';

function getCryptoInstance(): Crypto {
  if (typeof window !== 'undefined' && window.crypto) {
    return window.crypto;
  }
  if (typeof globalThis !== 'undefined' && globalThis.crypto) {
    return globalThis.crypto;
  }
  throw new Error('Web Crypto API no disponible en este entorno.');
}

/**
 * Derives an AES-GCM 256-bit CryptoKey using PBKDF2 with 100,000 iterations
 */
async function deriveEncryptionKey(cryptoInst: Crypto, salt: Uint8Array): Promise<CryptoKey> {
  const enc = new TextEncoder();
  const passphrase = (typeof process !== 'undefined' && process.env?.VAULT_MASTER_KEY) 
    ? process.env.VAULT_MASTER_KEY 
    : DEFAULT_SALT_SEED;

  const keyMaterial = await cryptoInst.subtle.importKey(
    'raw',
    enc.encode(passphrase),
    { name: 'PBKDF2' },
    false,
    ['deriveKey']
  );

  return await cryptoInst.subtle.deriveKey(
    {
      name: 'PBKDF2',
      salt: salt as any,
      iterations: 100000,
      hash: 'SHA-256'
    },
    keyMaterial,
    { name: 'AES-GCM', length: 256 },
    false,
    ['encrypt', 'decrypt']
  );
}

/**
 * Encrypts a sensitive plaintext string (e.g. API Key or Connection ID)
 * Output format: ENC_V1:<salt_hex>:<iv_hex>:<ciphertext_hex>
 */
export async function encryptData(plaintext: string): Promise<string> {
  if (!plaintext) return '';
  const cryptoInst = getCryptoInstance();
  const enc = new TextEncoder();

  const salt = cryptoInst.getRandomValues(new Uint8Array(16));
  const iv = cryptoInst.getRandomValues(new Uint8Array(12)); // 96-bit IV recommended for AES-GCM
  const key = await deriveEncryptionKey(cryptoInst, salt);

  const encryptedBuffer = await cryptoInst.subtle.encrypt(
    { name: 'AES-GCM', iv: iv as any },
    key,
    enc.encode(plaintext)
  );

  const saltHex = Array.from(salt).map(b => b.toString(16).padStart(2, '0')).join('');
  const ivHex = Array.from(iv).map(b => b.toString(16).padStart(2, '0')).join('');
  const cipherHex = Array.from(new Uint8Array(encryptedBuffer)).map(b => b.toString(16).padStart(2, '0')).join('');

  return `ENC_V1:${saltHex}:${ivHex}:${cipherHex}`;
}

/**
 * Decrypts a ciphertext string generated by encryptData
 * If string is not encrypted (legacy or plain), returns original string safely
 */
export async function decryptData(encryptedStr: string): Promise<string> {
  if (!encryptedStr) return '';
  if (!encryptedStr.startsWith('ENC_V1:')) {
    return encryptedStr; // Return plain text if not encrypted
  }

  const parts = encryptedStr.split(':');
  if (parts.length !== 4) {
    throw new Error('Formato de cifrado ENC_V1 inválido o corrupto.');
  }

  const [, saltHex, ivHex, cipherHex] = parts;
  const salt = new Uint8Array(saltHex.match(/.{1,2}/g)?.map(b => parseInt(b, 16)) || []);
  const iv = new Uint8Array(ivHex.match(/.{1,2}/g)?.map(b => parseInt(b, 16)) || []);
  const cipherBytes = new Uint8Array(cipherHex.match(/.{1,2}/g)?.map(b => parseInt(b, 16)) || []);

  const cryptoInst = getCryptoInstance();
  const key = await deriveEncryptionKey(cryptoInst, salt);

  const decryptedBuffer = await cryptoInst.subtle.decrypt(
    { name: 'AES-GCM', iv: iv as any },
    key,
    cipherBytes
  );

  return new TextDecoder().decode(decryptedBuffer);
}

/**
 * Mask an API key or sensitive identifier for UI display
 * e.g. "KEY018...f9a"
 */
export function maskSensitiveKey(val?: string, visibleChars = 4): string {
  if (!val) return '••••••••••••';
  if (val.length <= visibleChars * 2) return '••••••••••••';
  return `${val.slice(0, visibleChars)}••••••••${val.slice(-visibleChars)}`;
}
